### ISSUE TITLE
Highlighting Problems

### ISSUE THREAD

**Issue by ghost** [garysieling/jquery-highlighttextarea#12]
This sounds like a great plugin.  However, I cannot get it to highlight the proper text.  See attached screen snippet (trying to highlight the words " and " & "artist").  It is highlighting the correct line but not the correct word.  I am using the Twitter Boostrap framework with jquery, jqueryui.
![textarea1](https://f.cloud.github.com/assets/590286/174850/26e907c6-7b2c-11e2-9a91-e98b669b7490.png)

**Comment by yourfriendpr** [comment]
I am using the latest version and still facing this issue. highlight marker is shifted when there is a scrollbar.. 
are there any fixes for this?

**Comment by luckyrome** [comment]
Can you provide browser/OS combo and example? @yourfriendpr

**Comment by yourfriendpr** [comment]
Apologies for the delayed response.

It's happening on all browsers on windows 7
Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Firefox 52.5.3
IE 11.0.9600.18860CO
