### ISSUE TITLE
highlight style drifts on zoomed page

### ISSUE THREAD

**Issue by insano10** [garysieling/jquery-highlighttextarea#32]
Using the example from the demo,  the background highlight drifts to the right with every word present in the box. This makes the styled highlighted area not line up with the text it is highlighting.
I'm using jquery 2.1 and bootstrap 3.1.1. The text area is not inheriting any styles from parent elements.

for example:

![hello_drift](https://cloud.githubusercontent.com/assets/7420159/4726428/78dc4eba-5962-11e4-8a8c-e33d13984895.png)

       <textarea id="demo-custom" cols="50" rows="3" style="background: none;">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at massa non erat convallis vulputate molestie nec dui. Donec auctor blandit nibh quis luctus. Donec tincidunt auctor consequat.
       </textarea>

        <script>
        $('textarea').highlightTextarea({
            words: ['Lorem ipsum', 'vulputate'],
            id: 'demoCustom'
        });
    </script>

    <style>
        #demoCustom mark {
            padding:0 3px;
            margin:-1px -4px;
            border-radius:0.5em;
            border:1px solid pink;
        }
    </style>

**Comment by adubrov** [comment]
I found that this bug appears only in Chrome and Safari (in FireFox everything is fine). Also I noticed that highlightTextarea-highlighter element has in style "line-height:" which is not necessary and if to remove it - the bug is disappears
