### ISSUE TITLE
Highlighted Word Click Event

### ISSUE THREAD

**Issue by elalemanyo** [garysieling/jquery-highlighttextarea#42]
Hi,
It is possible to trigger the Click event on a Highlighted word?

Thanks

**Comment by selamhabibi** [comment]
Hi,
I do not get to run the "on click" event example. I have tried:

```
...
<textarea cols="50" rows="6">Lorem ipsum dolor sit amet.</textarea>

<script>

$('textarea').highlightTextarea({
  words: ['Lorem ipsum'],
});

if(jQuery().highlightTextarea) {
  console.log('Highlight Textarea ready....');
  $('.highlightTextarea').on('click', 'mark', function() {
    console.log('Highlight Textarea on click');
  });
}

</script>
...
```

I am grateful for any help ...

..Thanks

**Comment by elalemanyo** [comment]
Hi,

Here is a simple demo: http://codepen.io/elalemanyo/pen/BNKebp

But I think that will be better if we can have some events. We need to change the z-index, otherwise we can not trigger the click event on the mark items.

**Comment by selamhabibi** [comment]
Hi,

many thanks! The simple demo works for me after the page loaded. But when i click into the  textarea and write some text I need to set the z-index to parent div again. Do you have a solution to solve this behavior.

Best regards

**Comment by rlamorea** [comment]
By using the css `pointer-events` property, you can make highlighted areas clickable, but all other areas of the textarea pass through.

Codepen example (based on @elalemanyo pen above)
http://codepen.io/anon/pen/NAomwG

**Comment by selamhabibi** [comment]
Thank you very much! That's exactly what I was looking for!

**Comment by rlamorea** [comment]
FWIW, I updated that pen to show how you get which mark (by index) and what text was clicked on (since I need to do that for my use case and figure it is generally useful)
